#!/bin/bash
# 推送代码到 GitHub 的脚本

echo "=== 推送代码到 GitHub ==="
echo ""
echo "请按照以下步骤操作："
echo ""
echo "1. 配置 GitHub 认证（选择一种方式）："
echo ""
echo "   方式 A：使用 GitHub Token（推荐）"
echo "   - 访问 https://github.com/settings/tokens"
echo "   - 生成新的 Personal Access Token（选择 repo 权限）"
echo "   - 运行以下命令："
echo "     git config --global credential.helper store"
echo "     git push origin main"
echo "     # 输入用户名和 Token"
echo ""
echo "   方式 B：使用 SSH Key"
echo "   - 生成 SSH key：ssh-keygen -t rsa -b 4096"
echo "   - 复制公钥：cat ~/.ssh/id_rsa.pub"
echo "   - 添加到 GitHub：https://github.com/settings/keys"
echo "   - 修改远程 URL："
echo "     git remote set-url origin git@github.com:hsliuping/TradingAgents-CN.git"
echo "     git push origin main"
echo ""
echo "2. 推送代码："
echo "   cd ~/TradingAgents-CN"
echo "   git push origin main"
echo ""
echo "3. 部署到 Render："
echo "   - 访问 https://render.com"
echo "   - 登录并连接 GitHub 仓库"
echo "   - 按照 RENDER_DEPLOY.md 中的说明配置环境变量"
echo ""
echo "=== 部署指南 ==="
echo ""
echo "详细步骤请查看：~/TradingAgents-CN/RENDER_DEPLOY.md"
